### ISSUE TITLE
Your account is STOLEN and ABUSED by the very platform!

### ISSUE THREAD

**Issue by jbluv** [gmission/gmission#2]
Hi! I'm also a user, or rather victim, of the very platform.

I noticed that the platform admin **stole and abused** your account to make money via Xianyu. Please check the those strange repos that **"you"** starred and forked:

![c1](https://user-images.githubusercontent.com/76879803/104671850-90cbb400-5719-11eb-87b6-b05e12cf0e2e.jpg)

![c2](https://user-images.githubusercontent.com/76879803/104671858-95906800-5719-11eb-9052-da4150e3af46.jpg)

**Comment by freeznet** [comment]
@chenzhao so your account has been pwned?

**Comment by chenzhao** [comment]
> @chenzhao so your account has been pwned?

seems a token is leaked…

**Comment by chenzhao** [comment]
> Hi! I'm also a user, or rather victim, of the very platform.
> 
> 
> 
> I noticed that the platform admin **stole and abused** your account to make money via Xianyu. Please check the those strange repos that **"you"** starred and forked:
> 
> 
> 
> ![c1](https://user-images.githubusercontent.com/76879803/104671850-90cbb400-5719-11eb-87b6-b05e12cf0e2e.jpg)
> 
> 
> 
> ![c2](https://user-images.githubusercontent.com/76879803/104671858-95906800-5719-11eb-9052-da4150e3af46.jpg)
> 
> 
> 
> 

Hi, thanks a lot. It seems  my personal account token is leaked.
